# AMBERCOM
# Amber-tinted flavor of Encom OS
# author: @kverb
inherits = "encom"

[palette]

bg = "#0F1014"          # nearly black
bg2 = "#3e322a"         # dark brown
primary1 = "#f7dabe"    # "amber" light
primary2 = "#f4cda7"    # a little darker
primary3 = "#f1c091"    # darker still
primary4 = "#4a4139"    # very dark amber
# TODO: this teal clashes
secondary = "#00a595"   # Encom teal
bseconday = "#00d8c3"   # bright teal
tertiary = "#b0e0e6"    # Encom primary color (cyan)
btertiary = "#66e1f1"   # Encom primary slightly darker
red = "#C71585"         # "medium violet red"
whitespace = "#3f3730"  # one shade darker than primary4
