theme = "encom"

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
k = { j = "normal_mode" } # Maps `kj` to exit insert mode

[keys.normal]
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"
"D" = "kill_to_line_end"
"A-D" = "kill_to_line_start"
y = { y = ["extend_to_line_bounds", "yank"] }

[keys.select]
"C-j" = ["extend_to_line_bounds", "delete_selection", "paste_after", "select_mode"]
"C-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "select_mode"]

[editor]
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
bufferline = "multiple"
color-modes = true
true-color = true
end-of-line-diagnostics = "hint"


[editor.statusline]
left = ["mode", "spinner"]
center = ["diagnostics"]
right = [ "file-name", "separator", "selections", "separator","position", "separator", "file-type"]
separator = ""
mode.normal = ""
mode.insert = ""
mode.select = ""

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

# requires helix 25.01+
[editor.inline-diagnostics]
# Minimum severity to show a diagnostic on the primary cursor's line.
# Note that `cursor-line` diagnostics are hidden in insert mode.
cursor-line = "error"
