theme = "term16_dark"

[keys.insert]
"A-x" = "normal_mode" # Maps Alt-X to enter normal mode
k = { j = "normal_mode" } # Maps `jk` to exit insert mode

[keys.normal]
"C-h" = "jump_view_left"
"C-l" = "jump_view_right"

[keys.select]
"C-j" = ["extend_to_line_bounds", "delete_selection", "paste_after", "select_mode"]
"C-k" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "select_mode"]

[editor]
gutters = ["diagnostics", "spacer", "line-numbers", "spacer", "diff"]
bufferline = "multiple"
color-modes = true
true-color = true


[editor.statusline]
left = ["mode", "spinner"]
center = ["diagnostics"]
right = [ "file-name", "separator", "selections", "separator","position", "separator", "file-type"]
separator = ""
mode.normal = ""
mode.insert = ""
mode.select = ""

[editor.lsp]
display-messages = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false
